# Generated by Django 6.0.1 on 2026-01-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_scannerdevice_remove_user_fingerprint_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fingerprint_hash',
            new_name='fingerprint_template',
        ),
    ]
